# Generated by Django 6.0.8 on 2026-09-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_offer_message_offer_offer_chat_offer_conv_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
