# Generated by Django 6.0.8 on 2026-09-11 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_seed_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('place_holder_value', models.CharField(blank=True, max_length=100, null=True)),
                ('listing_type', models.CharField(choices=[('text', 'Text'), ('choice', 'Choice')], default='text', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ListingChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_value', models.CharField(max_length=100)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='games.listing')),
            ],
        ),
    ]
