# Generated by Django 6.0.8 on 2026-09-11 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_listing_listingchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='games.game'),
        ),
    ]
