# Generated by Django 6.0.8 on 2026-09-11 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_listing_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='games.game')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
