# Generated by Django 6.0.8 on 2026-09-11 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('games', '0005_gamerank'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='game_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.gamerank'),
        ),
    ]
