# Generated by Django 6.0.8 on 2026-09-24 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_seed_banks'),
        ('users', '0002_user_clerk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_holder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='banks.bank'),
        ),
    ]
