# Generated by Django 6.0.8 on 2026-09-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='qpay_qr_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payment',
            name='qpay_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
