# Generated by Django 6.0.8 on 2026-09-23 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0007_game_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open for registration'), ('live', 'Live'), ('finished', 'Finished')], default='open', max_length=10)),
                ('prize_pool', models.CharField(max_length=100)),
                ('entry_fee', models.CharField(default='Үнэгүй', max_length=100)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=100)),
                ('total_slots', models.PositiveIntegerField(default=16)),
                ('filled_slots', models.PositiveIntegerField(default=0)),
                ('slot_unit', models.CharField(default='баг', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='games.game')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
    ]
