# Generated by Django 6.0.8 on 2026-09-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournamentregistration_leader_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='mode',
            field=models.CharField(default='Online', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rules',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_size',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
