# Generated by Django 6.0.8 on 2026-09-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_mlbbmatchconfig_tournamentmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='score_a',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='score_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
