# Generated by Django 6.0.8 on 2026-09-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_tournamentmatch_score_a_tournamentmatch_score_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='battle_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='mlbb_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (teams or room TBD)'), ('open', 'Room open'), ('live', 'Match in progress'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
    ]
