# Generated by Django 6.0.8 on 2026-09-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_poll_match_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='lobby_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
