# Generated by Django 6.0.8 on 2026-09-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_tournamentmatch_lobby_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (teams or room TBD)'), ('open', 'Room open'), ('live', 'Match in progress'), ('expired', 'Deadline expired'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
    ]
